=== ksdfg/mit-stuff/t8/wt/XML/patient.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="patient" type="Patient"/>
<xsd:complexType name="Patient">
  <xsd:sequence>
    <xsd:element name="id" type="xsd:integer" minOccurs="1"/>
    <xsd:element name="name" type="xsd:string"/>
	<xsd:element name="age" type="xsd:integer"/>
	<xsd:element name="dob" type="xsd:date"/>
	<xsd:element name="gender" type="xsd:string"/>
	<xsd:element name="email" type="xsd:string"/>
	<xsd:element name="address" type="Address"  minOccurs="0" maxOccurs="2"/>
	<xsd:element name="payment" type="Payment"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="Address">
	<xsd:all>
		<xsd:element name="street" type="xsd:string"/>
		<xsd:element name="city" type="xsd:string"/>
		<xsd:element name="zipcode" type="xsd:integer"/>
		<xsd:element name="state" type="xsd:string"/>
		<xsd:element name="country" type="xsd:string"/> 
	</xsd:all>
</xsd:complexType>

<xsd:complexType name="Payment">
	<xsd:choice>
		<xsd:element name="insurance" type="xsd:string"/>
		<xsd:element name="cash" type="xsd:string"/>
	</xsd:choice>
</xsd:complexType>

</xsd:schema>

=== ksdfg/mit-stuff/t8/wt/XML/patient.xml
<?xml version="1.0"?>
<patient xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="patient.xsd">
	<id>123</id>
	<name>Anand</name>
	<age>56</age>
	<dob>1940-03/12</dob>
	<gender>Male</gender>
	<email>anand@gmail.com</email>
	<address>
		<zipcode> 411037 </zipcode>
		<street> Gandhi road </street>
		<city>Banglore</city>
		<state>Karnataka</state>
		<country>India</country>
	</address>
	<payment>
		<cash>123</cash>
	</payment>
</patient>
